### ISSUE TITLE
Discovery FLHook 3.0.0 - DSAce not publicly available

### ISSUE THREAD

**Issue by FLHookDev** [zibbizor/FLHook#13]
While this is technically not a bug, I would not know where to contact you regarding gaining access to DSAce. I have been using and modifying the FLHook within this repo (thanks by the way :) but after reading the files concerning DSAce it says that it's only allowed among a select few. I was wondering whether I could gain access to continuing with our project. 

Regards,
FLHD

P.S. (Yes I made an account just to request this :P )

**Comment by dsyalex** [comment]
Who are you and why should you have access?

**Comment by zibbizor** [comment]
It won't be public.
