### ISSUE TITLE
Can't figure out how to build 'alley' plugin

### ISSUE THREAD

**Issue by dsyalex** [zibbizor/FLHook#8]
I tried installing boost and moving the files to a directory called boost in the root of the repository, but I get this error:
LNK1104	cannot open file 'libboost_date_time-vc140-mt-1_60.lib'

**Comment by zibbizor** [comment]
Read "boost dependencies.txt" in the FLHook repository root. All the instructions are there.

**Comment by dsyalex** [comment]
Oops, I should've checked through those files. Thanks.

PS: skylink.dl.sourceforge.net seems to be broken, so I replaced skylink with kent
